# This is a basic workflow to help you get started with Actions

name: Fetch Data
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  fetchstatedata:
    runs-on: ubuntu-latest
    name: Fetch abstract
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run Script
        run: |
          pip install -r requirements.txt
          python stockfish.py
      - name: Commit Report
        continue-on-error: true
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git commit -am "Automatically Updated abstract"
          git push
